server:
  port: 890

eureka:
  client:
#    因为当前是消费者，所以不需要注册进注册中心
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/  # 集群版

# 设置 feign 客户端超时时间(OpenFile默认支持ribbon)
ribbon:
  #处理请求的超时时间，默认为5秒
  ReadTimeout: 5000
  #连接建立的超时时长，默认5秒
  ConnectTimeout: 5000

logging:
  level:
    # feign 日志以什么级别监控哪个接口
    com.atguigu.springcloud.Service.PaymentFeignService: debug
